project:
  resources:
    - "lec_slides/2026/VibeCodingExample.html"
    - "lec_slides/2026/RP/RP01.html"
  render:
    - "!lec_slides/2026/VibeCodingExample.qmd"
    - "lec_slides/2026/**/*.md"
    - "lec_slides/2026/**/*.qmd"
    - "lec_slides/2026/**/*.pdf"
    - "!assets/*.qmd"
    - "!lec_slides/2024/*.qmd"
    - "!lec_slides/2024/**/*.qmd"
    - "!homeworks/2024/*.qmd"
    - "!homeworks/2024/**/*.qmd"

filters:
  - assets/filters/ListArrow.lua
