project:
  render:
    - "lec_slides/2026/"
    - "!assets/*.qmd"
    - "!lec_slides/2024/*.qmd"
    - "!lec_slides/2024/**/*.qmd"
    - "!homeworks/2024/*.qmd"
    - "!homeworks/2024/**/*.qmd"

filters:
  - assets/filters/ListArrow.lua
