---
title: "HW2"
author: "Your name"
date: "`r format(Sys.time(), '%Y年%m月%d日 %R')`"
output:
  tufte::tufte_html:
    citation_package: natbib
    tufte_features: ["fonts", "background", "italics"]
    toc: true
    includes:
      in_header: "../program/MathShorthand.html"
  pdf_document:
    latex_engine: xelatex
    fig_width: 7
    fig_height: 6
    fig_caption: true
    includes:
      in_header: "../program/MathShorthand.html"
urlcolor: blue
linkcolor: red
header-includes:
    - \usepackage{amsmath}
    - \usepackage{amssymb}
    - \usepackage{amsfonts}
    - \usepackage{bookmark} 
    - \usepackage{natbib} 
    - \usepackage{xltxtra} 
    - \usepackage{zxjatype} 
    - \usepackage[ipa]{zxjafont} 
    - \usepackage{marginnote}
bibliography: c:/seiro/settings/Tex/seiro.bib
link-citations: yes
# setwd(path <- "c:/seiro/docs/external/seishin/lec_slides/2024/"); rmarkdown::render(paste0(path, "hw2.Rmd"))
#### Below are git bash commands.  ####
#### git init
#### git config --global user.name "SeiroIto"
#### git remote add origin https://github.com/SeiroIto/Ramadan.git  ## specify remote
#### git branch -M main
#### Close git once and start again. 
#### Before running below, create .gitignore and place it in c:/data/Ramadan/submit2024/
#### git add c:/data/Ramadan/submit2024/program c:/data/Ramadan/submit2024/save   ## this adds files to track
#### git add c:/data/Ramadan/submit2024/program   ## for most times, use this 
#### Below may not be necessary if .gitignore works as intended. 
#### git ls-tree -r main --name-only ## list all tracked files
#### git commit -am "initial commit"
#### git push -f origin main  ## push files to remote
#### if error with push fatal: the remote end hung up unexpectedly, run below
#### git config http.postBuffer 2000000000
#### git push -f origin main  ## push files to remote
---

```{css, echo=F}
DBlue {
  color: dodgerblue;
}
Blue {
  color: blue;
}
.SeiroBenign {
  background-color: #FFEBCD;
  padding: 0.5em; /*文字まわり（上下左右）の余白*/
  /* border: 1px solid yellow; */
  /* font-weight: bold; */
}
```

```{r setup, echo = F, results = "hide"} 
#### include = F <==> echo=F & results = F
#### renv::init()
#### library(renv)
library(knitr)
library(tufte)
#### invalidate cache when the tufte version changes
knitr::opts_chunk$set(
  tidy = FALSE, cache.extra = packageVersion('tufte'), 
  margin_references = TRUE,
  #### remove leading hashes in html output
  comment = "", 
  echo = T, cache = F, 
  class.source = "SeiroBenign", class.output = "SeiroLightGreen"
  )
options(htmltools.dir.version = FALSE, width = 100)
gc()
```

## pandocのインストール

* windows: https://www.oresamalabo.net/entry/2022/07/24/165638
* iOS: https://docs.zettlr.com/ja/installing-pandoc/#macos
* iPadOS=RStudio Cloud: ローカルへのインストールは不要

## tinytexのインストール

Rで下記を実行します。

```{r install tinytex}
install.packages("tinytex")
@

## .gitignorの作成

```
#### This is gitignore for Seishin
/_extensions/
/_freeze/
@


```{r ShowMemUse, echo = F}
ShowMemUse(decreasing = T, limit = 10)
```

